version: '3.7'
services:
  webapp:
    container_name: webapp_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./:/webapp
      - /node_modules