version: '3.7'
services:
  webapp:
    container_name: webapp_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    expose:
      - ${VITE_PORT}
    volumes:
      - ./:/webapp
      - ./node_modules

